### ISSUE TITLE
Doconce does not show installed version

### ISSUE THREAD

**Issue by Daniel-M** [hplgit/doconce#10]
Details
---------
Doconce does not show the installed version with the _--help_ option

> $ doconce --help    
> Usage: doconce command [optional arguments]    
> commands: format insertdocstr old2new_format gwiki_figsubst remove_inline_comments latin2html sphinx_dir subst replace replace_from_file clean help latex_header latex_footer guess_encoding change_encoding bbl2rst split_rst list_labels teamod sphinxfix_localURLs make_figure_code_links grab spellcheck ptex2tex   ...

Neither there is an option _--version_.

Knowing the doconce version would be useful when reading the online documentation in order to know how much accordance to expect.

My system info
--------------
**Os:** Debian Jessie 8 ( Testing )
**Doconce version:** 0.7.3-1 installed from official Debian repository for US. (the testing repository)

**Comment by hplgit** [comment]
Fixed!

Note that Debian packages are old and out of sync with the documentation. Always install from this repo. A note about this fact is inserted under "Installation".
