### ISSUE TITLE
ref and cite in doconce notebooks

### ISSUE THREAD

**Issue by lrhgit** [hplgit/doconce#101]
I have a problem with the rendering of citations (cite) and references to equations in python notebooks generated by doconce, e.g. 
https://github.com/lrhgit/uqsa_tutorials/blob/master/sensitivity_introduction.ipynb

The links in the references are pointing to the correct location, it is just the rendering that seems to be wrong. 
Examples:
1) The first citation in the Introduction section
2) The first equation ref in the section 'A simple linear model'.  Here the link does not have the equation number. 

Do I have to provide some options to 'doconce format ipynb my_file.do.txt' or is this a bug?

**Comment by KGHustad** [comment]
I think this may be a limitation in the Jupyter notebook format. It is possible that we may be able to create a workaround, but for now you will either have to use (non-interactive) HTML or avoid numeric references. 

Btw, do note that notebook rendering on github.com is less thorough, so all equations are labeled with (1). If you instead use nbviewer, the rendering is much better and equations are labeled with increasing numbers.

https://nbviewer.jupyter.org/github/lrhgit/uqsa_tutorials/blob/master/sensitivity_introduction.ipynb

**Comment by lrhgit** [comment]
With the new nbextension we are almost there (jupyter nbextension enable equation-numbering/main)

The only thing remaining is that the cross-refs should be (\ref{eq_lbl}) rather than the current (ref(eq_lbl)). I hope this may be an easy fix in the "doconce format ipynb" parsing?

**Comment by KGHustad** [comment]
I don't think we need to use that extension since we already detect equations and assign them tags (1, 2, etc.) like LaTeX would. (It might not render correctly if the extension is not installed.) 

References to equations are just links, which jump to the correct position in the notebook when clicked. It seems that these links are still shown with the label instead of the equation number. I will fix this shortly.

**Comment by KGHustad** [comment]
If you're still seeing incorrect equation references, feel free to reopen this issue @lrhgit
