### ISSUE TITLE
Unclear if conda package is close to be as current as GH master

### ISSUE THREAD

**Issue by michaelaye** [hplgit/doconce#108]
On the documentation webpage it is indicated that GH installs are recommended vs zip/tarballs.
But as a conda package is offered as well, it would be good to know if that package is being held close to GH master, maybe via an automatic packaging pipeline, or if GH master installs are still getting the highest recommendation.
Thanks for this intriguing tool! Dr. Langtangen was sooo proficient, I could imagine this project to become one of his many legacies. May he rest in piece.

**Comment by KGHustad** [comment]
The conda packages should be quite close to master. Installation via conda is probably the easiest way of installing DocOnce, as long as the disk space is not a major concern (Anaconda alone is ~ 2GB).

**Comment by michaelaye** [comment]
Anaconda is not a required for using conda, so that's not necessarily a problem. Thanks for your answer.
