### ISSUE TITLE
reveal slides print-pdf does not work as expected

### ISSUE THREAD

**Issue by lexnederbragt** [hplgit/doconce#111]
reveal.js has an option to add `?print-pdf` to the slideshow url, and this allows for slides to be printed to a PDF (see https://github.com/hakimel/reveal.js#pdf-export).

reveal slides made with doconce allow adding `?print-pdf`, but it results in a collapsed stack of slides rather than something that can be printed to PDF.

I have an (reproducible) example, using my 'Minimal doconce demo' [repo](https://github.com/lexnederbragt/doconce_demo): 

slides: https://lexnederbragt.github.io/doconce_demo/slide1/slide1.slides.html

print-pdf: https://lexnederbragt.github.io/doconce_demo/slide1/slide1.slides.html?print-pdf

commands used

```
doconce format html slide1.do.txt --html_output=slide1.slides --pygments_html_style=perldoc --keep_pygments_html_bg SLIDE_TYPE=reveal SLIDE_THEME=beige --skip_inline_comments \
	&& doconce slides_html slide1.slides reveal --html_slide_theme=beige
```
(see https://github.com/lexnederbragt/doconce_demo/blob/master/slide1/slide1.commands.sh)

**Comment by KGHustad** [comment]
It seems like there are some pretty strict requirements for this to work:
>Presentations can be exported to PDF via a special print stylesheet. This feature __requires that you use Google Chrome or Chromium and to be serving the presention from a webserver__. 

I tried their example, and that didn't really work either. 

LaTeX slides are the probably the best option for printing,if you want to print your slides, but I usually just make an ordinary document with the same content (no slide layout).

**Comment by lexnederbragt** [comment]
Thanks. I am opting for a solution making a plain html version of the slides as a handout.

**Comment by lexnederbragt** [comment]
Workaround: use deck2pdf https://github.com/melix/deck2pdf to generate a pdf file of slides.
