### ISSUE TITLE
Generated makefile make.py shows SyntaxErrors

### ISSUE THREAD

**Issue by Daniel-M** [hplgit/doconce#12]
Details
----------
Doconce makefile _make.py_ created with the command 

> $ doconce makefile example.do.txt html pdflatex    

Fails when executed as

> $ python make.py    

The error message is

>File "make.py", line 19     
>    print 'Command failed.' %% cmd     
>                                          ^         
>SyntaxError: invalid syntax     

How to reproduce the issue
----------------------------------

Create file example.do.txt with the contents:

>TITLE: Example     
>AUTHOR: Example     
>DATE: Feb 2015     
>TOC: on       
>     
>========= Example =========     
>Lorem ipsum dolor...     

Execute commands

> $ doconce makefile example.do.txt html pdflatex    
> $ python make.py   

System info
--------------
**Os:** Debian Jessie 8 ( Testing )
**Doconce version:** DocOnce version 1.0.2 Installed from official git repository downloaded and compiled the 10 Feb of 2015

**Comment by hplgit** [comment]
The generation of make.py was very experimental and hardly tested. It now works for pdflatex, html, and sphinx. A warning about the experimental nature of the make.py script is issued.
