### ISSUE TITLE
Enhancement to DocOnce? Yasnippet,  LaTeX shortcuts when editing Doconce. 

### ISSUE THREAD

**Issue by ofenerci** [hplgit/doconce#120]
Hello, 
I am using AucTeX inside Emacs with[ Yasnippet ](https://github.com/joaotavora/yasnippet) for my LaTeX documents. I am changing to more versatile Doconce for editing. I would like to use some AucTeX commands (such as C-c C-e for selecting LaTeX environment) or Yasnippet. 

A few questions in my mind:
1) I am considering write some Yasnippet templates for Doconce (inserting headings, environments, etc.). Has anybody written it before? If not, I will try it myself.

2) I would like to use AucTeX's commands (inserting environment, RefTeX, etc). Is It possible to use those features inside DocOnce environment?

3) There is already nice doconce mode for [Emacs](https://github.com/larstvei/Doconce-mode). This one look more promising than original hplgit's `doconce-mode.el` file. But I am not able to load AucTeX mode with this mode. What I have tried is below, but it fails to use both modes together.
```
    (add-hook 'doconce-mode-hook 'LaTeX-mode)
    (add-hook 'LaTeX-mode 'doconce-mode)
    (add-to-list 'auto-mode-alist '("\\.do.txt\\'" . LaTeX-mode))
```

**Comment by KGHustad** [comment]
I'm afraid I cannot provide any support for the Emacs extensions for DocOnce. 

1. I'm only aware of the Emacs extensions made by HPL and Lars Tveito, which you have already found.

**Comment by ofenerci** [comment]
For the future reference for people  who are using Emacs: 
There is another Emacs extension which provides rich snippets  and shortcuts. 

https://github.com/slemeshevsky/emacs-starter-kit/tree/master/src
