### ISSUE TITLE
Converting to DocBook

### ISSUE THREAD

**Issue by worldmind** [hplgit/doconce#124]
DocBook is semantic markup too and it has some tools for converting to another formats (for example i read about converter to ePub).
Will be great if DocOnce can be converted to DocBook.

**Comment by KGHustad** [comment]
You can convert a DocOnce file to DocBook via pandoc.
```
doconce format pandoc some_document
```
And then refer to the pandoc documentation for instructions on how to convert the pandoc file to DocBook.
