### ISSUE TITLE
bibliography from BibTeX

### ISSUE THREAD

**Issue by ricopicone** [hplgit/doconce#125]
I don't know the reason for using publish instead of BibTeX format for the bibliography, but I'm having difficulty getting even the most minimal BibTeX document to convert to publish format. I save a file `doc.bib` with contents

```tex
@book{Larson2013,
	Author = {Larson, M.G. and Bengzon, F.},
	Publisher = {Springer Berlin Heidelberg},
	Series = {Texts in Computational Science and Engineering},
	Title = {The Finite Element Method: Theory, Implementation, and Applications},
	Year = {2013}}
```

When I run `publish import doc.bib` I am told every attribute is missing (e.g. author, year, etc.).

I'm hoping someone can help me get this most basic example working. However, I'd also like to understand why Doconce is relying on publish, which seems to be a package in need of further development and maturity (I could be wrong?). Thanks!

**Comment by ricopicone** [comment]
It turns out that the capital letters that my BibTeX database manager BibDesk uses for the first letter of each key is the problem. That leaves my second question (why publish?) and generates a new one: is there a recommended BibTeX database manager for macOS that's more compatible with publish? Thanks!

**Comment by ricopicone** [comment]
It looks like Mendeley uses lowercase keys. I'll miss BibDesk's simplicity, but I'm willing to make the switch for now. Still, I'm curious about why Publish is integral to Doconce.

**Comment by KGHustad** [comment]
publish is very (perhaps *too*) strict about the format of the `.bib` file. I don't think there's any good reason to why it can't be more tolerant.

publish has the advantage of being a pure Python package, and we also have influence over the project with the abiilty to get changes incorporated fairly quickly if needed.

**Comment by ricopicone** [comment]
Thanks for the explanation, @KGHustad! It's not a big deal, but I think it's a bit of a barrier to getting started with _Doconce_. It's not surprising that a package trying to do so much has a few strict requirements.
