### ISSUE TITLE
#include markdown file?

### ISSUE THREAD

**Issue by ricopicone** [hplgit/doconce#126]
I'm writing documentation for a GitHub project in _Doconce_ and would like to have the first section simply be the `README.md` of the main project. I found in the documentation that _Doconce_ documents can be written in Markdown and, separately, that subfiles can be included in a main _Doconce_ document with `#include`. However, it's not clear to me how to (or if it is possible to) include a markdown file in a main _Doconce_ `.do.txt` file. What I'm trying is (in the `docs` directory, where the _Doconce_ documentation resides):

    # #include "../README.md"

However, the result doesn't appear to be formatted as if the interpreter knows the included README is in markdown. Is there an `#include` option flag or something? I couldn't find one in the documentation. Thanks for any help!

**Comment by ricopicone** [comment]
It occurs to me that we could go the other way: perhaps the first section of the _Doconce_ document could be saved as `README.md`. Is there a way to export a section as a separate markdown document?

**Comment by KGHustad** [comment]
You could have `README.do.txt` as a separate file and include it in your documentation. 
And then you could generate `README.md` with
```
doconce format pandoc README --github_md
```
