### ISSUE TITLE
conda install does not give doconce command

### ISSUE THREAD

**Issue by karinlag** [hplgit/doconce#131]
Hi!

I've got anaconda3 on my biolinux (aka ubuntu) linux machine. I've opted to install with conda because of this. However, I don't get the expected doconce command, and the system says it's not installed:

karinlag@enki:~$ conda install doconce
Fetching package metadata ...........
Solving package specifications: .

`#` All requested packages already installed.
`#` packages in environment at /home/karinlag/projects/vi/src/anaconda3:
`#`
doconce                   1.4.3                    py35_0    conda-forge
karinlag@enki:~ $ doconce
The program 'doconce' is currently not installed. You can install it by typing:
sudo apt-get install doconce
karinlag@enki:~ $ 

Am I doing something wrong during the install?

**Comment by KGHustad** [comment]
If you installed doconce into a particular conda environment, you may need to activate that environment which will ensure that the directory where doconce is installed is included in `PATH`. 

See https://conda.io/docs/user-guide/tasks/manage-environments.html for more information

**Comment by karinlag** [comment]
I finally figured out what this was caused by: apparently I had managed to put several anaconda installs on my machine, and they did not play well with eachother. Thanks for giving me a nudge in the right direction!
