### ISSUE TITLE
Creating reports from jupyter notebook analyses with doconce

### ISSUE THREAD

**Issue by karinlag** [hplgit/doconce#132]
First, apologies if this is a FAQ, however, I have not been able to figure out this issue by reading the docs so far (which may very well just be because I haven't understood enough of how doconce works yet).

I am making a bioinformatics analyses pipeline, and I have analyses at the end of this pipeline that I'd like to run. I also want these analyses to be available as jupyter notebooks so that the users can rerun and modify the analyses as needed - note. As far as I've understood, I can have these analyses written in doconce, and get notebooks produced from these, which the user can then run. However, I have heard rumours that I can also have doconce execute these analyses, and produce pdfs/html/whatever from these. I have yet to find out how to do this from the documentation. I realize that if this is indeed possible, it should be described somewhere, and I would be grateful if somebody could point me to where to find the relevant docs.

**Comment by KGHustad** [comment]
This feature is not considered stable yet, hence there is no mention of it in the documentation. If you want to try it out, you need to use the `dev` branch. Code execution is enabled with `--execute`.

**Comment by karinlag** [comment]
Thanks for letting me know, and for pointing me in the right direction!
