### ISSUE TITLE
elsevier.cls in the generated latex file from doconce

### ISSUE THREAD

**Issue by zaxebo1** [hplgit/doconce#14]
for writing a research paper , I have to write in latex STRICTLY USING "elsevier.cls"
( please refer http://www.elsevier.com/author-schemas/the-journal-document-class-elsart  
                      http://www.elsevier.com/author-schemas/latex-instructions           
                    http://mirrors.ctan.org/macros/latex/contrib/elsarticle/doc/elsdoc.pdf
 )

Now, Can i write my research paper in "doconce", so as to "generate the latex" while which only uses "Journal documentclass **elsarticle** " from the "elsevier.cls" . So that the research paper can be submitted to an elsevier journal.

**Comment by hplgit** [comment]
The Elsevier style is enabled in latex by 

```
doconce format pdflatex mydoc --latex_style=elsevier
```
(Not much tested.)

**Comment by zaxebo1** [comment]
can i find a good documentation **for newbie** which tells that - how to write "customized latex styles"?

**Comment by zaxebo1** [comment]
and any hello-world type documentation on how can i write my plugins/extensions for doconce
