### ISSUE TITLE
Wrong parsing of URLs from IPython/Jupyter into DocOnce documents

### ISSUE THREAD

**Issue by Daniel-M** [hplgit/doconce#140]
Parsing of jupyter notebooks as `doconce ipynb2doconce notebookfile` performs wrong parsing of URLs, for example, the text (as markdown in the notebook) `[Daniel Mejía R.](http://daniel-m.github.io)`  parses to `"Daniel Mejía R.": "(http://daniel-m.github.io)"` which is wrong and should be `"Daniel Mejía R." : "http://daniel-m.github.io"`. Happened with several links, the text is a particular example

**Comment by KGHustad** [comment]
Thanks for reporting this.
