### ISSUE TITLE
Norwegian language error on mac: locale=nb_NO.UTF-8 must be installed

### ISSUE THREAD

**Issue by solveignaess** [hplgit/doconce#141]
Hi!

Trying to select `--language=Norwegian ` on my mac, I got the following error message:
`error: unsupported locale setting`
`locale=nb_NO.UTF-8 must be installed`

It turned out that the locale `nb_NO.UTF-8` has a different name on mac, namely:  `no_NO.UTF-8`. Changing this in doconce.py solved the problem.

Just wanted to let you know.=) 

Solveig

**Comment by KGHustad** [comment]
I thought I fixed this with [this commit](https://github.com/hplgit/doconce/commit/c70dd37fb4106ad429f11b8c6981a14eb8ff3f4e). What changes did you make to `doconce.py`?

**Comment by solveignaess** [comment]
I must've overlooked this commit when looking for an answer yesterday! Turns out that I hadn't updated my version of doconce since May.=/ Sorry about that.
