### ISSUE TITLE
** error: --latex_style=Springer_llncs not registered

### ISSUE THREAD

**Issue by hoanganhduc** [hplgit/doconce#143]
Hi! I got this error when using comman `doconce format latex report --latex_style=Springer_llncs`. Does anyone know how to fix it? I am familiar with Springer LNCS so I really want to use that style for writing.
Thanks!

**Comment by KGHustad** [comment]
Unfortunately, `Springer_llncs` is currently not fully supported (which should have been noted in the manual).

It's easy to just add the relevant `llncs.cls` file to DocOnce and enable it. It might require further modifications to work well, but I don't have the time to do that kind of testing now. If you would be willing to test it, we could enable it.

**Comment by hoanganhduc** [comment]
Thanks for the reply. I tried to modify the file `latex.py` in the doconce source code to make `Springer_llncs` available. I am not quite good at coding, so there may be several bugs. The modified file is [here](https://github.com/hoanganhduc/doconce/blob/master/lib/doconce/latex.py) if anyone interests in using Springer LNCS. A demo of my paper using this style is [here](https://hoanganhduc.github.io/doconce/test/Springer-LNCS-Demo/).
