### ISSUE TITLE
Numbering in sphinx

### ISSUE THREAD

**Issue by mikaem** [hplgit/doconce#155]
Hi

Just a question really. The default behaviour when creating sphinx is to rename all references. Referring to the [rst_bib](https://github.com/hplgit/doconce/blob/f0a317ecc87c637b410ea3a1e8196ce14f38df37/lib/doconce/rst.py#L414) signature:

    def rst_bib(filestr, citations, pubfile, pubdata, numbering=True):
        """
        Replace doconce citations and bibliography with reST syntax.
        If numbering is True, the keys used in the bibliography are
        replaced by numbers (RefX). This will often look better.
        """

How is it possible to set numbering to `False` without hardcoding this in the signature? I cannot find any way to overload this keyword argument.

**Comment by KGHustad** [comment]
There is presently no command line option to control this setting.

**Comment by mikaem** [comment]
That would be great:-)
