### ISSUE TITLE
Python 3 does not have string.uppercase

### ISSUE THREAD

**Issue by lexnederbragt** [hplgit/doconce#157]
I am trying to compile the book from https://github.com/hplgit/setup4book-doconce. I used `2to3` to convert `scripts.py` to Python 3. But now I run into an issue with doconce's `latex.py`:

```
 File "/anaconda3/envs/doconce_1_4_5_nbformat_4_3/lib/python3.6/site-packages/doconce/latex.py", line 2617, in latex_quiz
    text += '\\textbf{%s}. ' % string.uppercase[i]
```

Comparing https://docs.python.org/2.7/library/string.html with https://docs.python.org/3.6/library/string.html it seems `string.uppercase` is removed, probably in favor of `string.ascii_uppercase`.

Not sure whether this needs fixing...

**Comment by dumblob** [comment]
Wouldn't https://docs.python.org/3.6/library/stdtypes.html#str.upper be more fitting the purpose?
