### ISSUE TITLE
python notebooks and matplotlib inline 

### ISSUE THREAD

**Issue by lrhgit** [hplgit/doconce#159]
test.do.txt with content 

!bc pycode
import matplotlib
!ec

yields after doconce format ipynb test.do.txt

%matplotlib inline
import matplotlib

in the resulting notebook. That is %matplotlib inline is auto-included before any 'import matplotlib'.  For certain notebooks with ipwidgets this causes problems. 

Q: Is there any ways to avoid the auto-inclusion of the %matplotlib inline?

**Comment by KGHustad** [comment]
I just added an option `--ipynb_disable_mpl_inline`, which will disable the automatic insertion of `%matplotlib inline` before the first line where matplotlib is imported.

**Comment by lrhgit** [comment]
Takk skal du ha Kristian. Supert. Godt jobba.



lr
