### ISSUE TITLE
format pdflatex --sections_up to prompt sections to chapters

### ISSUE THREAD

**Issue by schuang** [hplgit/doconce#16]
When I use 7 `=` for section titles in .do.txt source and run `doconce format pdflatex --sections_up`, `\section{}` in the .tex file is promoted to `\chapter{}` as expected, but `\documentclass` still uses `article` (not `book`), causing pdflatex command to fail (e.g. `article` does not support `\chapter`)

I could get around this problem by some preprocessing, but it would be great if `article` can also be promoted to `book` when 7 `=` is prompted to 9 by `--sections_up`, to avoid pdflatex errors.

Test:
```
$ cat intro.do.txt 
======= Introduction =======

This is the intro.

$ doconce format pdflatex intro --sections_up
translating doconce text in intro.do.txt to pdflatex
transforming sections: section to chapter...
transforming sections: subsection to section...
transforming sections: subsubsection to subsection...
output in intro.p.tex
$ doconce ptex2tex intro
output in intro.tex
$ cat intro.tex
...<snipped>
\documentclass[%
twoside,                 % oneside: electronic viewing, twoside: printing
final,                   % or draft (marks overfull hboxes, figures with paths)
10pt]{article}
...<snipped>
\chapter{Introduction}
```

**Comment by hplgit** [comment]
Fixed!
