### ISSUE TITLE
Collapse solutions, answers, hints don't work on Chrome for iOS

### ISSUE THREAD

**Issue by henriasv** [hplgit/doconce#166]
Exercises compiled with bootstrap bootswatch.  Glyph icons linking to the collapse/uncollapse feature of solutions, answers and hints don't work (are not pressable) in Chrome for iOS. (I suspet that this problem ranges wider, but I only tested for Chrome for iOS).

**Comment by henriasv** [comment]
The example doesn't work on Chorme/Safari on an iPhone 8. Maybe a workaround could be to make the text (solution/hint/answer) a link for the collapse as well

**Comment by KGHustad** [comment]
Yeah, that seems like reasonable workaround. I don't have the time to implement and test it now, but you could give it a go if you want.
