### ISSUE TITLE
http --> https for netdna.bootstrapcdn.com

### ISSUE THREAD

**Issue by lexnederbragt** [hplgit/doconce#170]
I use `--html_style=bootswatch_readable` a lot and have noticed that the javascript sometimes does not work unless I change all `http:/netdna.bootstrapcdn.com` in the html fil to `https:/netdna.bootstrapcdn.com`. I see 102 occurrences of `http:/netdna.bootstrapcdn.com` in the repo. Can these all safely be changed to `https:/netdna.bootstrapcdn.com`?

**Comment by KGHustad** [comment]
It should be safe to replace those.

**Comment by KGHustad** [comment]
But this is only an issue in `doc/`. New documents will use https, since this was fixed some time ago.

**Comment by lexnederbragt** [comment]
Thanks. Once I have tome to try the latest doconce I'll verify that the problem has disappeared. Closing for now.
