### ISSUE TITLE
BIBFILE and publish issues?

### ISSUE THREAD

**Issue by reckoner** [hplgit/doconce#174]
My understanding is that `publish` is still used within `doconce` from using `BIBFILE`. The problem is that https://bitbucket.org/logg/publish has a `lxml` dependency that requires `libiconv.so.2` and I cannot get that working on Ubuntu 18 bionic. 

Is there a way to avoid using `publish` with `BIBFILE`? It seems that `publish` it lightly supported so I don't know if keeping it in `doconce` will make sense going forward. I am using Python 3.7.

Thanks!

**Comment by KGHustad** [comment]
If you have trouble installing DocOnce, the easiest and recommended installation method is via `conda`.

How did you install lxml?

Bibliography support in DocOnce currently requires publish. That might change in the next major version of DocOnce.

**Comment by reckoner** [comment]
I did not install lxml directly. It came with some other package.
