### ISSUE TITLE
conda paver via doconce conflicts with tensorflow

### ISSUE THREAD

**Issue by reckoner** [hplgit/doconce#175]
I don't know if it's possible to change the feedstock for doconce to avoid this?

    UnsatisfiableError: The following specifications were found to be in conflict:
      - paver
      - tensorflow

This is for Python 3.7.

**Comment by KGHustad** [comment]
I don't think this is related to DocOnce or paver.

```
$ conda create -n test python=3.7 tensorflow
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - python=3.7
  - tensorflow -> protobuf==3.0.0b2 -> python=2.7 -> readline=6.2
  - tensorflow -> protobuf==3.0.0b2 -> python=2.7 -> sqlite=3.13
  - tensorflow -> protobuf==3.0.0b2 -> python=2.7 -> tk=8.5
Use "conda info <package>" to see the dependencies for each package.
```

There doesn't seem to be any tensorflow package for Python 3.7 on neither the official Anaconda channels nor conda-forge.
https://anaconda.org/anaconda/tensorflow/files
https://anaconda.org/conda-forge/tensorflow/files

**Comment by reckoner** [comment]
Thanks! `conda` is confusing me.
