### ISSUE TITLE
Pagebreak for PDF

### ISSUE THREAD

**Issue by Fenrihr** [hplgit/doconce#178]
Hi,
How can i insert `pagebreaks` every chapter or section?

**Comment by KGHustad** [comment]
Some LaTeX styles will do this automatically. Use `--latex_style` to set the LaTeX style. (See [the manual](http://hplgit.github.io/doconce/doc/pub/manual/manual.html))

If you want to force a pagebreak, you could add a line with `\newpage` in the DocOnce document, which should make it into the `.tex` file.
