### ISSUE TITLE
New version of book built with doconce

### ISSUE THREAD

**Issue by unpingco** [hplgit/doconce#179]
https://github.com/unpingco/Python-for-Probability-Statistics-and-Machine-Learning-2E

Doconce is also cited therein and mentioned in the acknowledgments. You already have the previous version of this on your site. This is for the updated version. The repository above has a new image of the front cover, if you're interested to include it. Just FYI!

**Comment by KGHustad** [comment]
Thank you for the notice and for mentioning DocOnce in the acknowledgements. 
The image with the book covers is a collage, so it's slightly inconvenient to update it. If you want to update it, feel free to submit a PR, otherwise I'll just leave it as is for now.
