### ISSUE TITLE
bibitem vs. bibtex

### ISSUE THREAD

**Issue by schuang** [hplgit/doconce#18]
In http://hplgit.github.io/doconce/doc/pub/manual/html/manual.html#bibliography-references
there are several places it mentions the `bibitem` command. I thought the `bibtex` command is more standard for this purpose? (e.g. TeX Live does not seem to have the `bibitem` command.)

For example,

![screen shot 2015-03-12 at 5 49 57 pm](https://cloud.githubusercontent.com/assets/451425/6631254/426d3fd6-c8e0-11e4-8715-8a2780c8724c.png)

**Comment by hplgit** [comment]
You are absolutely right. This is an old and ugly typo, should be `bibtex`. Fixed.

Thanks!!
