### ISSUE TITLE
Syntax example on web page is broken.

### ISSUE THREAD

**Issue by MrZoraman** [hplgit/doconce#187]
In the Highlights section on the front page there is (see [syntax example](http://hplgit.github.io/teamods/writing_reports/_static/report/do.txt.html)). The link is broken.

**Comment by RoyiAvital** [comment]
I think it is still broken:

![image](https://user-images.githubusercontent.com/7347975/77823657-cf9e6800-710d-11ea-962d-37f65cd29839.png)

I mean where is says:
> syntax example
