### ISSUE TITLE
Issues with generating markdown for slate

### ISSUE THREAD

**Issue by deem0n** [hplgit/doconce#22]
Slate is very similar to Nikola, but specialized on API docs: https://github.com/tripit/slate
Somehow I think that using doconce to generate markdown for Slate might be a good idea, especially if one want to generate LaTeX/PDF as well.

Slate has it's own flavor of markdown: https://github.com/tripit/slate/wiki/Markdown-Syntax
which use PHP style tables :-(

Finally I managed to use `doconce format pandoc myfile --github_md` which gives
1. Verbose HTML tables in generated markdown which is fine for Slate
2. ``` for source code parts which is exactly what Slate expect

Two problems still remain:

1. DocOnce support only dozen programming languages compared to quite many supported by Slate http://rouge.jayferd.us/demo

Seems I can hack pandoc.py to add what I need (Java), but what will happen when I will generate say LaTex format ?

2. Strangely enough Slate use verbose HTML for Notes and Warnings! It seems that some special syntax in DocOnce would be helpfull to generate those <aside></aside> tags for Slate and something different for LaTeX.

Is it feasible to have special option --slate_md to generate correct markdown for Slate and still valid LaTeX from the DocOnce format ?

**Comment by hplgit** [comment]
1. It's straightforward to add more languages. What I need is a mapping from file extensions to language names in Pygments. I can also offer this mapping as a dict in a file that the user prepares.

2. That should be easy. Just provide precise examples. We can very well have a --slate_md option.

**Comment by deem0n** [comment]
Ok, thanks. Will adjust it for my needs.

**Comment by hplgit** [comment]
It will probably not take me more than 20 min to implement your needs if I get a list of languages and an example...or I can guide you where to make the adjustments. You may send me info on hpl@simula.no.

**Comment by deem0n** [comment]
Thank you mate !

I was in search for good documentation tool where 'good' means a lot of different things ;-) Checked ApiBlueprint, doconce, slate and raml.

ApiBlueprint has nicely working preview plugin for Atom, but not so flexible in writing docs and even API itself. Personally for me it looks very limiting.

slate has sexy HTML version but is just static site generator. It does very nice thing: one page documentation which looks like complete site with different pages :-)

doconce is nice and easy to use, supports various output formats but has not so much tooling for API validation and checks. I would also recommend to check Pillar, which is similar to doconce, but written in Smalltalk and is used to produce books. And if you are old enough to use Smalltalk you should love TeX ;-)

RAML is mostly to design API, but has ability to produce documentation with markdown. I finally chosen RAML as it allows to split all process into chunks and assemble all kind of documentation from it with includes. My personality feels ok with YAML syntax which is not comfortable for everyone, compared to markdown. It is quite hard to get PDF version though, as RAML designed for API checking and modeling in live environments where you can make requests and see responses from automatically generated mocks. So RAML is mostly for live, online tools. But with some care you can get HTML and even PDF.

I am pleased with doconce and would consider it for writing massive documentation and learning materials where printed version is a must. But for now I need a mix of API and it's description where RAML suits my needs better.

**Comment by hplgit** [comment]
OK, thanks for clarifying!

FYI, Doconce was never meant for API doc, although it is used as an
improved reStructuredText in Python doc strings for Sphinx API
documentation, but that is limited to Python. The point is to produce one
version of the code with rst doc for Sphinx and one version with plain
untagged text for pydoc API documentation.

Doconce has teaching material as the main target.

Hans Petter
