### ISSUE TITLE
Incorporate matplotlib defaults?

### ISSUE THREAD

**Issue by unpingco** [hplgit/doconce#30]
This blog post:

http://bkanuka.com/articles/native-latex-plots/

shows how to incorporate native looking defaults into matplotlib figures. Can this be accommodated in doconce?

Thanks!

**Comment by hplgit** [comment]
If you have

```
FIGURE: [fig, frac=0.9] caption
```
and there is a file `fig.pgf`, the generated output is now `\input{fig.pgf}`, otherwise a `fig.pdf` is used with `\includegraphics` the usual way. Hope it works!
