### ISSUE TITLE
references not being generated correctly in pdf but are OK with html

### ISSUE THREAD

**Issue by nagordon** [hplgit/doconce#32]
I have a doconce source file [test2.do.txt](https://github.com/nagordon/technotes/blob/master/doconce/test2/test2.do.txt) that creates an [html file](https://github.com/nagordon/technotes/blob/master/doconce/test2/test2.html) and latex and then [pdf](https://github.com/nagordon/technotes/blob/master/doconce/test2/test2.pdf). The references are created correctly with the html file but not the latex file. Any Ideas?

Thanks in advance.

**Comment by hplgit** [comment]
The problem is that there are two BIBFILE: specifications in the test2.do.txt file. BibTeX then gives an error message. I've inserted a test on multiple BIBFILE: specifications so now you get an error message. With one BIBFILE: I was able to get a normal Bibliography.

**Comment by nagordon** [comment]
My installation must be faulty because I cannot replicate your results. The pdf referenced above is the result of the updated test2.do.txt file. There are not errors when I run ```pdflatex``` either

**Comment by nagordon** [comment]
Figured it out, I forgot 
```
bibtex test2
```
in the make.sh file
Thanks again for your trouble
