### ISSUE TITLE
conda install did not install ipython notebook

### ISSUE THREAD

**Issue by nagordon** [hplgit/doconce#33]
Using Ubuntu 14.10, it appears that, after installing [miniconda](http://conda.pydata.org/miniconda.html), and then running the conda package install ```conda install --channel johannr doconce```, it is missing the ipython notebook for some operations. Once I ran ```conda install ipython-notebook```, all the ipynb operations worked with doconce. Perhaps this could be included in the conda package?

**Comment by johannesring** [comment]
Thanks for the suggestion. I have added ipython-notebook to the requirements for doconce and uploaded a new package.
