### ISSUE TITLE
Issue at the doconce manual

### ISSUE THREAD

**Issue by Daniel-M** [hplgit/doconce#36]
I have not found other mean to report a minor typo en the doconce manual I've just read.
the section available at
http://hplgit.github.io/doconce/doc/pub/manual/html/manual.html#exercise-1-compute-integrals
Look at the excercise b), it describes the integral as

> $e^{-at}\sin(wx)$   

but I'm guessing that you meant

>$e^{-ax}\sin(wx)$   

My guess is based on the solution proposed and the python source code provided which reads
> F = sp.integrate(sp.exp(-a*x)*sp.sin(w*x), x)   

Sorry if this is not the best way of reporting a typo, but I did not found other way.

D.M.

**Comment by hplgit** [comment]
Thank you very much! This is a fine place to report typos and errors.
