### ISSUE TITLE
'future' is a dependency of  'preprocess', move line 89 before 69...

### ISSUE THREAD

**Issue by map0logo** [hplgit/doconce#45]
Hi Hans, 

I found a bug on the installation script
https://github.com/hplgit/doconce/blob/master/doc/src/manual/install_doconce.py

You have to move installation of "future" python in line 89 to some place before line 69, because 'future' is a dependency of  'preprocess'. Otherwise returns "ImportError no module named past.builtins".

Regards.

**Comment by hplgit** [comment]
Thanks for pointing this out! The bug is fixed.
