### ISSUE TITLE
utf8x issues

### ISSUE THREAD

**Issue by unpingco** [hplgit/doconce#51]
I keep getting this error when I try pdflatex

```
The package inputenc has already been loaded with options:
  [utf8x]
There has now been an attempt to load it with options
  [utf8]
Adding the global options:
  utf8x,utf8
to your \documentclass declaration may fix this.
Try typing  <return>  to proceed.
```

I'm not sure how to fix this with doconce. 

Any help appreciated.

**Comment by hplgit** [comment]
The problem is probably due to use of some special latex style that does a `\usepackage[utf8]{inputenc}`. Need the .tex file at least, preferably a minimum DocOnce source and the compilation command to track down the problem.

One can fix the error by

```
doconce replace '[utf8x]' '[utf8]' mydoc.tex
```

**Comment by unpingco** [comment]
Okay. Let me finish around for it. You have given me enough to get started.

By the way, I did notice that utf8x is also in the source code

    https://github.com/hplgit/doconce/blob/master/lib/doconce/latex.py

I don't know if that matters.
