### ISSUE TITLE
Typo in DocOnce Description

### ISSUE THREAD

**Issue by elemurmel** [hplgit/doconce#54]
While a friend and me are currently working on a lightweight german description on DocOnce for school I tripped over a minor typo in the "Markdown to HTML conversion" section:

In the codeblock you wrote "m2html" instead of "md2html" like in the sentence before for the conversion from pandoc to html.

Hope this helps and keep up the amazing work on DocOnce.

**Comment by hplgit** [comment]
Thank you very much!

**Comment by elemurmel** [comment]
Me again, sorry :-)
Found another one:
reStructuredText chapter
-> The sentence before the third codeblock says "unovonv" instead of "unoconv"
