### ISSUE TITLE
subsubsections converted to paragraph in latex

### ISSUE THREAD

**Issue by stevosn** [hplgit/doconce#71]
Hey!

I am trying to use `=== heading ===`  to be converted as a `\subsubsection{heading}` in latex, but it's converted to a paragraph. Is there a way to force it to use subsubsections?

I use doconce version 1.2.

Thanks!

S

**Comment by hplgit** [comment]
The convention is that subsubsections become paragraphs in latex (only three levels of headings - many styles for books for instance stick to such layout), but you can always edit and tailor the latex code. You need to substitute all paragraphs by subsubsections:

```
doconce format pdflatex mydoc --latex_code_style=vrb
doconce subst 'paragraph\{(.+)\}' 'subsubsection{\g<1>}' mydoc.tex
```
The side effect is that `__Paragraph headings.__` are turned into subsubections... One can think of a hack where there is some indicator text in the paragraph headings that is used to recognize these headings and turn them to paragraph again...

**Comment by stevosn** [comment]
Thanks, that works fine! Although I don't understand the substitution
command, yet. I guess I can find that in the doc?

Thanks again!
S

**Comment by hplgit** [comment]
Check out http://hplgit.github.io/doconce/doc/pub/trouble/trouble.html#___sec58

`doconce subst` performs substitutions based on *regular expressions*, so you need to understand the basics of regular expressions to use this command.

**Comment by stevosn** [comment]
Okay!

Thanks a lot!
S

On 06.04.2016 10:23, Hans Petter Langtangen wrote:
> Check out
> http://hplgit.github.io/doconce/doc/pub/trouble/trouble.html#___sec58
> 
> |doconce subst| performs substitutions based on /regular expressions/,
> so you need to understand the basics of regular expressions to use this
> command.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/hplgit/doconce/issues/71#issuecomment-206214513>
> 

-- 
Steve Simmert
Gartenstraße 25
72147 Nehren
