### ISSUE TITLE
[Urgency:Low] Minor typo in doconce documentation

### ISSUE THREAD

**Issue by Daniel-M** [hplgit/doconce#73]
At the end of the section [Sphinx or reStructuredText Output](http://hplgit.github.io/doconce/doc/pub/tutorial/html/tutorial.html#sphinx-or-restructuredtext-output) of the online documentation,  the command

`sudo apt-get install unovonv libreoffice libreoffice-dmaths`

should be replaced for

`sudo apt-get install unoconv libreoffice libreoffice-dmaths`

describing the packages to be installed for libreoffice/openoffice integration in Debian systems. (provided that `unoconv` is for converting between libreoffice formats)

**Note:** I've tried to make a pull request to change this at the source of the docs, but couldn't find the associated source .do.txt so i made this issue.

Thanks!

**Comment by hplgit** [comment]
Many thanks!
