### ISSUE TITLE
problem generating latexpdf

### ISSUE THREAD

**Issue by sakhan007** [hplgit/doconce#75]
I am sorry if this is not a appropriate place to ask this but I am having trouble recreating a document in doconce which was initially produced with pure latex code. 
I tried inserting `\usepackage` statements in the resulted `*.p.tex` file but this requires heavy editing.. Are there any better solutions? Do we always have to insert the `\usepackage` commands manually in the resulted `*.tex` file? Thanks for your time.

latex file: http://pastebin.com/FH5QCCB3
my attempt test.do.txt : http://pastebin.com/0YvS563H
my newcommands_keep.tex file: http://pastebin.com/JpG6WKLJ

**Comment by KGHustad** [comment]
I think you've missed the point of DocOnce somewhat. `!bt` is meant to be used for LaTeX mathematics environments (such as `align` and `equation`), not to encapsulate an entire LaTeX document. Normal text in a DocOnce document should not recide within a `!bt`-block.

I'd recommend having a look at http://hplgit.github.io/doconce/doc/pub/manual/html/manual.html#latex-blocks-of-mathematical-text to see a demonstration of how `!bt` is meant to be used.
