### ISSUE TITLE
em-dash not working consistently for HTML output

### ISSUE THREAD

**Issue by MartinHeroux** [hplgit/doconce#81]
I was preparing a blog post and used the following command to generate the HTML file:
`doconce format html git_lessons.do.txt`

In the text I used two em-dashes (i.e., ---), but only one of them got properly converted to an em-dash; the other (the first in the text below), was represented as three short dashes in HTML. 

Has anyone else experienced this problem?  

**DOCONCE FILE CONTENT**  
`A recent article by Perez-Riverol *et al* cite{Perez-Riverol2016} outlines 10 simple rules to get the most of Git and GitHub ---an online service that hosts repositories and provides additional functionality for collaborative projects--- in the context of scientific projects.`

**Comment by KGHustad** [comment]
The syntax is defined such that there can't be whitespace on either side of the em-dash. See http://hplgit.github.io/doconce/doc/pub/manual/manual.html#___sec43

> there are no spaces around the em-dash

**Comment by MartinHeroux** [comment]
Thanks for pointing me to the right place, much appreciated.  

I guess what confused me was that my second em-dash did have a space to the right of it and it did render correctly.
