### ISSUE TITLE
doconce and sphinx 1.4.8

### ISSUE THREAD

**Issue by yoons1** [hplgit/doconce#87]
After upgrading sphinx to 1.4.8 on Anaconda, doconce generation to sphinx doc does not work.  I get the following message:

> [Interrupted.]
> could not run tmp_sphinx_gen to generate sphinx directory
> Abort! (add --no_abort on the command line to avoid this abortion)

Going back to sphinx 1.3.5 makes doconce generate files as expected.

**Comment by KGHustad** [comment]
I was able to build a minimal example with Sphinx 1.4.8. Could you provide more information?

**Comment by yoons1** [comment]
Sorry for the late reply.

My command line:  doconce sphinx_dir  theme=haiku my_file

results in the following:

-------------------------------------------------------------------------------------
$>echo Making sphinx-rootdir
Making sphinx-rootdir

$>mkdir sphinx-rootdir

$>sphinx-quickstart  0<tmp_sphinx_gen.inp
Welcome to the Sphinx 1.5.2 quickstart utility.

Please enter values for the following settings (just press Enter to
accept a default value, if one is given in brackets).

Enter the root path for documentation.
> Root path for the documentation [.]:
You have two options for placing the build directory for Sphinx output.
Either, you use a directory "_build" within the root path, or you separate
"source" and "build" directories within the root path.
> Separate source and build directories (y/n) [n]:
Inside the root directory, two more directories will be created; "_templates"
for custom HTML templates and "_static" for custom stylesheets and other static
files. You can enter another prefix (such as ".") to replace the underscore.
> Name prefix for templates and static dir [_]:
The project name will occur in several places in the built documentation.
> Project name: > Author name(s):
Sphinx has the notion of a "version" and a "release" for the
software. Each version can have multiple releases. For example, for
Python the version is something like 2.5 or 3.0, while the release is
something like 2.5.1 or 3.0a1.  If you don't need this dual structure,
just set both to the same value.
> Project version []: > Project release [1.0]:
If the documents are to be written in a language other than English,
you can select a language here by its language code. Sphinx will then
translate text that it generates into that language.

For a list of supported codes, see
http://sphinx-doc.org/config.html#confval-language.
> Project language [en]:
The file name suffix for source files. Commonly, this is either ".txt"
or ".rst".  Only files with this suffix are considered documents.
> Source file suffix [.rst]:
One document is special in that it is considered the top node of the
"contents tree", that is, it is the root of the hierarchical structure
of the documents. Normally, this is "index", but if your "index"
document is a custom template, you can also set this to another filename.
> Name of your master document (without suffix) [index]:
Sphinx can also add configuration for epub output:
> Do you want to use the epub builder (y/n) [n]:
Please indicate if you want to use one of the following Sphinx extensions:
> autodoc: automatically insert docstrings from modules (y/n) [n]: > doctest: automatically test code snippets in doctest blocks (y/n) [n]: > intersphinx: link between Sphinx documentation of different projects (y/n) [n]: > todo: write "todo" entries that can be shown or hidden on build (y/n) [n]: > coverage: checks for documentation coverage (y/n) [n]: > imgmath: include math, rendered as PNG or SVG images (y/n) [n]: > mathjax: include math, rendered in the browser by MathJax (y/n) [n]: > ifconfig: conditional inclusion of content based on config values (y/n) [n]: > viewcode: include links to the source code of documented Python objects (y/n) [n]: > githubpages: create .nojekyll file to publish the document on GitHub pages (y/n) [n]:
A Makefile and a Windows command file can be generated for you so that you
only have to run e.g. `make html' instead of invoking sphinx-build
directly.
> Create Makefile? (y/n) [y]: > Create Windows command file? (y/n) [y]:
[Interrupted.]
could not run tmp_sphinx_gen to generate sphinx directory
Abort! (add --no_abort on the command line to avoid this abortion)

--------------------------------------------------------------------------

The text 

> githubpages: create .nojekyll file to publish the document on GitHub pages (y/n) [n]:

is the only difference between the output from sphinx 1.3.5 and higher version.
