### ISSUE TITLE
bib2rst.py can't import bib4txt

### ISSUE THREAD

**Issue by puterleat** [hplgit/doconce#9]
see error:

ben@Bens-MacBook-Pro ~/dev/doconce !510 # python bin/bib2rst.py 
Traceback (most recent call last):
  File "bin/bib2rst.py", line 26, in <module>
    from bibstuff import bib4txt
ImportError: cannot import name bib4txt

This is after running python setup.py install on head.

**Comment by hplgit** [comment]
The translation of bibtex to rst is very old doconce code that should be remove - and now it is. We rely on the Publish package to produce various kinds of formats for bibliographies. If you pull, there is only one executable left: bin/doconce.

**Comment by puterleat** [comment]
Are there any docs on how to convert from bib to rst?

**Comment by hplgit** [comment]
I just found bib2rst.py some years ago by googling. Think it originates from University of Washington.

If you use Publish from https://bitbucket.org/logg/publish, bib to rst is easy. You first import .bib to Publish and then export to rst. (This is the approach used in doconce.)

**Comment by puterleat** [comment]
Ah - many thanks.
