### ISSUE TITLE
How to use Tufte-LaTeX style?

### ISSUE THREAD

**Issue by reckoner** [hplgit/doconce#94]
How can I persuade doconce to use this latex style?

https://tufte-latex.github.io/tufte-latex/

Seems like it need more than --latex_style, AFAIK.

Thanks!

**Comment by KGHustad** [comment]
You may be able to set up a script to edit the .tex file produced by DocOnce as needed. 

From page 33 in http://mirrors.ctan.org/macros/latex/contrib/tufte-latex/sample-book.pdf

> The following headings are not supported: `\subsubsection` and `\subparagraph`.

So I guess you would have to replace those as well.
