### ISSUE TITLE
conda recipe on johannr needs updating

### ISSUE THREAD

**Issue by reckoner** [hplgit/doconce#97]
Looks as if

    sudo conda install --channel johannr doconce

needs to be updated with preprocess from here.

    https://github.com/hplgit/preprocess

Just fyi.

**Comment by KGHustad** [comment]
DocOnce has been added to conda-forge (by @johannesring), so the one on the `johannr` channel is not being updated anymore, as far as I know. 

See install instructions at https://github.com/conda-forge/doconce-feedstock

**Comment by johannesring** [comment]
Yes, that is correct - DocOnce has been added to conda-forge, but some dependencies are still waiting to be added (among them preprocess).
